-- generated by tableshape.codegen -- do not edit
local type, pairs, ipairs, next, tostring = type, pairs, ipairs, next, tostring
local getmetatable, setmetatable = getmetatable, setmetatable
local string_match = string.match
local FailedTransform = {}
local clone_state = function(state_obj)
if type(state_obj) ~= "table" then return {} end
local out = {}
for k, v in pairs(state_obj) do out[k] = v end
local mt = getmetatable(state_obj)
if mt then setmetatable(out, mt) end
return out
end
local c1 = {}
local t1, t2, t3
t3 = function(value, state)
if not (true) then return FailedTransform end
local v, s = value, clone_state(state)
local existing = s["vals"]
if type(existing) == 'table' then
local copy = {}
for ek, ev in pairs(existing) do copy[ek] = ev end
copy[#copy + 1] = v
s["vals"] = copy
else
s["vals"] = { v }
end
return v, s
end
t2 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
local transformed = false
local out = {}
for mk, mv in pairs(value) do
local new_mk, new_mv = mk, mv
if not (type(mk) == "string") then return FailedTransform end
do
local s
new_mv, s = t3(mv, state)
if new_mv == FailedTransform then return FailedTransform end
state = s
end
if new_mk ~= mk or new_mv ~= mv then transformed = true end
if new_mk ~= nil then out[new_mk] = new_mv end
end
if transformed then return out, state end
return value, state
end
t1 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
local dirty = false
local out = {}
for rk in pairs(value) do
if c1[rk] == nil then
local item = value[rk]
local tuple, s = t2({[rk] = item}, state)
if tuple == FailedTransform then return FailedTransform end
state = s
local nk = tuple and next(tuple)
if nk == nil then
dirty = true
else
if nk ~= rk or tuple[nk] ~= item then dirty = true end
out[nk] = tuple[nk]
end
end
end
if dirty then return out, state end
return value, state
end
local check_value = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected {  }" end
if type(s) == 'table' then return s end
return true
end
local transform = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected {  }" end
if type(s) == 'table' then return v, s end
return v
end
return {
check_value = check_value,
transform = transform,
repair = transform
}
