-- generated by tableshape.codegen -- do not edit
local type, pairs, ipairs, next, tostring = type, pairs, ipairs, next, tostring
local getmetatable, setmetatable = getmetatable, setmetatable
local string_match = string.match
local FailedTransform = {}
local c1 = {}
local t1, t2
t2 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
for mk, mv in pairs(value) do
if not (type(mk) == "string") then return FailedTransform end
if not (type(mv) == "string") then return FailedTransform end
end
return value, state
end
t1 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
for rk in pairs(value) do
if c1[rk] == nil then
local tuple_in = {[rk] = value[rk]}
if not ((t2(tuple_in, state)) ~= FailedTransform) then return FailedTransform end
end
end
return value, state
end
local check_value = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected {  }" end
if type(s) == 'table' then return s end
return true
end
local transform = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected {  }" end
if type(s) == 'table' then return v, s end
return v
end
return {
check_value = check_value,
transform = transform,
repair = transform
}
