-- generated by tableshape.codegen -- do not edit
local type, pairs, ipairs, next, tostring = type, pairs, ipairs, next, tostring
local getmetatable, setmetatable = getmetatable, setmetatable
local string_match = string.match
local FailedTransform = {}
local sorted_pairs = function(t)
local keys = {}
for k in pairs(t) do keys[#keys + 1] = k end
table.sort(keys, function(a, b)
local ta, tb = type(a), type(b)
if ta ~= tb then return ta < tb end
if ta == "number" or ta == "string" then return a < b end
if ta == "boolean" then return not a and b end
return tostring(a) < tostring(b)
end)
local i = 0
return function()
i = i + 1
local k = keys[i]
if k ~= nil then return k, t[k] end
end
end
local t1
t1 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
for mk, mv in sorted_pairs(value) do
if not (type(mk) == "string") then return FailedTransform end
if not (type(mv) == "number") then return FailedTransform end
end
return value, state
end
local check_value = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected map of type \"string\" -> type \"number\"" end
if type(s) == 'table' then return s end
return true
end
local transform = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected map of type \"string\" -> type \"number\"" end
if type(s) == 'table' then return v, s end
return v
end
return {
check_value = check_value,
transform = transform,
repair = transform
}
