-- generated by tableshape.codegen -- do not edit
local type, pairs, ipairs, next, tostring = type, pairs, ipairs, next, tostring
local getmetatable, setmetatable = getmetatable, setmetatable
local string_match = string.match
local FailedTransform = {}
local clone_state = function(state_obj)
if type(state_obj) ~= "table" then return {} end
local out = {}
for k, v in pairs(state_obj) do out[k] = v end
local mt = getmetatable(state_obj)
if mt then setmetatable(out, mt) end
return out
end
local sorted_pairs = function(t)
local keys = {}
for k in pairs(t) do keys[#keys + 1] = k end
table.sort(keys, function(a, b)
local ta, tb = type(a), type(b)
if ta ~= tb then return ta < tb end
if ta == "number" or ta == "string" then return a < b end
if ta == "boolean" then return not a and b end
return tostring(a) < tostring(b)
end)
local i = 0
return function()
i = i + 1
local k = keys[i]
if k ~= nil then return k, t[k] end
end
end
local t1, t2
t2 = function(value, state)
if not (true) then return FailedTransform end
local v, s = value, clone_state(state)
local existing = s["vals"]
if type(existing) == 'table' then
local copy = {}
for ek, ev in pairs(existing) do copy[ek] = ev end
copy[#copy + 1] = v
s["vals"] = copy
else
s["vals"] = { v }
end
return v, s
end
t1 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
local transformed = false
local out = {}
for mk, mv in sorted_pairs(value) do
local new_mk, new_mv = mk, mv
if not (type(mk) == "string") then return FailedTransform end
do
local s
new_mv, s = t2(mv, state)
if new_mv == FailedTransform then return FailedTransform end
state = s
end
if new_mk ~= mk or new_mv ~= mv then transformed = true end
if new_mk ~= nil then out[new_mk] = new_mv end
end
if transformed then return out, state end
return value, state
end
local check_value = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected map of type \"string\" -> anything tagged \"vals\"" end
if type(s) == 'table' then return s end
return true
end
local transform = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected map of type \"string\" -> anything tagged \"vals\"" end
if type(s) == 'table' then return v, s end
return v
end
return {
check_value = check_value,
transform = transform,
repair = transform
}
