-- generated by tableshape.codegen -- do not edit
local type, pairs, ipairs, next, tostring = type, pairs, ipairs, next, tostring
local getmetatable, setmetatable = getmetatable, setmetatable
local string_match = string.match
local FailedTransform = {}
local t1
t1 = function(value, state)
if (type(value) == 'string' and string_match(value, "^%d+$") ~= nil) then return value, state end
return FailedTransform
end
local check_value = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected pattern \"^%d+$\"" end
if type(s) == 'table' then return s end
return true
end
local transform = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected pattern \"^%d+$\"" end
if type(s) == 'table' then return v, s end
return v
end
return {
check_value = check_value,
transform = transform,
repair = transform
}
