-- generated by tableshape.codegen -- do not edit
local type, pairs, ipairs, next, tostring = type, pairs, ipairs, next, tostring
local getmetatable, setmetatable = getmetatable, setmetatable
local string_match = string.match
local FailedTransform = {}
local clone_state = function(state_obj)
if type(state_obj) ~= "table" then return {} end
local out = {}
for k, v in pairs(state_obj) do out[k] = v end
local mt = getmetatable(state_obj)
if mt then setmetatable(out, mt) end
return out
end
local c1 = {["id"] = true, ["name"] = true}
local t1, t2
t2 = function(value, state)
if not (type(value) == "string") then return FailedTransform end
local v, s = value, clone_state(state)
s["name"] = v
return v, s
end
t1 = function(value, state)
if type(value) ~= 'table' then return FailedTransform end
local dirty = false
local out = {}
do
local item = value["id"]
if not (type(item) == "number") then return FailedTransform end
out["id"] = item
end
do
local item = value["name"]
local v, s = t2(item, state)
if v == FailedTransform then return FailedTransform end
state = s
if v ~= item then dirty = true end
out["name"] = v
end
for rk in pairs(value) do
if c1[rk] == nil then return FailedTransform end
end
if dirty then return out, state end
return value, state
end
local check_value = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected { \"id\" = type \"number\", \"name\" = type \"string\" tagged \"name\" }" end
if type(s) == 'table' then return s end
return true
end
local transform = function(value, state)
local v, s = t1(value, state)
if v == FailedTransform then return nil, "expected { \"id\" = type \"number\", \"name\" = type \"string\" tagged \"name\" }" end
if type(s) == 'table' then return v, s end
return v
end
return {
check_value = check_value,
transform = transform,
repair = transform
}
